version: '2'

services:
  keycloak_dev:
    build:
      context: ./keycloak
      dockerfile: Dockerfile-dev
    volumes:
      - ./keycloak/theme:/opt/jboss/keycloak/themes/openremote
    environment:
      TZ: "Europe/Zurich"
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: DEBUG
    ports:
      - "8081:8080"
