# OpenRemote v3
#
# Profile that runs the vanilla stack on https://localhost using a self-signed SSL certificate,
# with username 'admin' and password 'secret'. There is no map data available in the vanilla
# system so the map tile server will not function. Persistent data is stored in a docker
# volume called postgresql-data between restarts, simply delete this volume to reset the
# system to an empty state.
#
# Please see profile/deploy.yml for configuration details for each service.
#
version: '2.4'

volumes:
  postgresql-data:

services:

  proxy:
    image: openremote/proxy:${DATE_TAG:-latest}
    extends:
      file: profile/deploy.yml
      service: proxy
    depends_on:
      manager:
        condition: service_healthy

  manager:
    image: openremote/manager:${DATE_TAG:-latest}
    extends:
      file: profile/deploy.yml
      service: manager
    depends_on:
      keycloak:
        condition: service_healthy

  keycloak:
    image: openremote/keycloak:${DATE_TAG:-latest}
    extends:
      file: profile/deploy.yml
      service: keycloak
    depends_on:
      postgresql:
        condition: service_healthy

  postgresql:
    image: openremote/postgresql:${DATE_TAG:-latest}
    extends:
      file: profile/deploy.yml
      service: postgresql
