version: '2'

services:
  manager:
    image: openremote/manager:latest
    links:
      - postgres
      - keycloak
    environment:
      TZ: "Europe/Zurich"
      DEV_MODE: 'false'
      DATABASE_CREATE_SCHEMA: 'true'
      IMPORT_SAMPLE_DATA: 'true'
      WEBSERVER_LISTEN_HOST: 0.0.0.0
      WEBSERVER_LISTEN_PORT: 8080
      IDENTITY_NETWORK_HOST: demo2.openremote.com
      IDENTITY_NETWORK_WEBSERVER_PORT: 80
      DATABASE_CONNECTION_URL: jdbc:postgresql://postgres/openremote
      KEYCLOAK_HOST: keycloak
      KEYCLOAK_PORT: 8080
    ports:
      - "8090:8080"
  keycloak:
    image: openremote/keycloak:latest
    links:
      - postgres:postgresql
    environment:
      TZ: "Europe/Zurich"
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: DEBUG
      POSTGRES_DATABASE: openremote
      POSTGRES_USER: openremote
      POSTGRES_PASSWORD: secret
  postgres:
    image: openremote/postgres:latest
    environment:
      TZ: "Europe/Zurich"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: openremote
