# Demo setup of OpenRemote v3
#
# This configuration works with https://www.docker.com/products/overview#/docker_toolbox
#
# Install Docker Toolbox and execute "docker-compose -p openremote -f profile/demo.yml up"
#
version: '2'
services:

  # The frontend proxy, terminates SSL/TLS connections and forwards them to the Manager backend.
  # TODO Document how to install sidecar letsencrypt container for production certificates, with shared volume mapping.
  haproxy:

    # Use installed or pull the latest image from Docker Hub.
    image: openremote/haproxy:latest

    environment:

      # It is important that all services have the same timezone and are time synchronized.
      # Bearer tokens are only valid for minutes, and authentication fails if Keycloak drifts.
      TZ: Europe/Zurich

      # This is a demo configuration with a self-signed dummy SSL certificate, baked into the image.
      HAPROXY_CONFIG: /etc/haproxy/demo/haproxy-demo.cfg

    # This service needs access to other services on the Docker network.
    links:
      - manager

    # Expose a public web service mapped to ports on the host.
    ports:
      - "80:80"
      - "443:443"

    # Configure logging of the container
    logging:
        options:
            max-size: 10m

  # The API gateway and Manager web application.
  manager:

    # Use installed or pull the latest image from Docker Hub.
    image: openremote/manager:latest

    environment:

      TZ: Europe/Zurich

      # If developer mode is enabled, all setup tasks will be executed on application startup.
      # This will clean all data in Keycloak and the Manager database, and then import demo/test
      # data. Some caching and other runtime performance-optimizations will also be disabled.
      DEV_MODE: 'false'

      # If you are not running in developer mode, and this is the first time you are starting
      # the application, you can configure which setup tasks you want to execute. Careful,
      # these tasks will clean and populate Keycloak and the Manager database with demo data!
      SETUP_INIT_CLEAN_DATABASE: 'true'
      SETUP_KEYCLOAK_ADMIN_PASSWORD: secret
      SETUP_IMPORT_DEMO_USERS: 'true'
      SETUP_IMPORT_DEMO_ASSETS: 'true'
      SETUP_IMPORT_DEMO_RULES: 'true'

      # Optional: Configure SMTP smart host for Keycloak, to send password reset emails etc.
      #SETUP_KEYCLOAK_EMAIL_HOST: smtp-host.demo.tld
      #SETUP_KEYCLOAK_EMAIL_USER: 'smtp-user'
      #SETUP_KEYCLOAK_EMAIL_PASSWORD: 'smtp-password'
      #SETUP_KEYCLOAK_EMAIL_PORT: 25
      #SETUP_KEYCLOAK_EMAIL_AUTH: 'true'
      #SETUP_KEYCLOAK_EMAIL_TLS: 'true'
      #SETUP_KEYCLOAK_EMAIL_FROM: 'noreply@demo.tld'

      # The public host name of this OpenRemote installation. This name is used in bearer tokens
      # and must be the name you access the web services under.
      IDENTITY_NETWORK_HOST: localhost

      # Set if SSL is enabled on the frontend reverse proxy and all internal proxies should assume https
      IDENTITY_NETWORK_SECURE: 'true'

      # The public port of this OpenRemote installation.
      IDENTITY_NETWORK_WEBSERVER_PORT: 443

      # The service-internal JDBC connection URL for the database service.
      DATABASE_CONNECTION_URL: jdbc:postgresql://postgresql/openremote

      # The database connection settings, passwords should be changed in production!
      DATABASE_USERNAME: openremote
      DATABASE_PASSWORD: CHANGE_ME_DB_USER_PASSWORD
      DATABASE_MIN_POOL_SIZE: 5
      DATABASE_MAX_POOL_SIZE: 20
      DATABASE_CONNECTION_TIMEOUT_SECONDS: 300

      # The service-internal host name and port of the identity provider.
      KEYCLOAK_HOST: keycloak
      KEYCLOAK_PORT: 8080

      # Optional: Console applications can register for push notifications through FCM.
      # NOTIFICATION_FIREBASE_URL: https://fcm.googleapis.com/fcm/send
      # NOTIFICATION_FIREBASE_API_KEY = '...'

      # Optional: Override built-in logging.properties with a file of your choice
      # LOGGING_CONFIG_FILE: /my/manager/logging.properties

    # This service needs access to other services on the Docker network.
    links:
      - postgresql
      - keycloak

    # Configure logging of the container, see config/logging.properties
    logging:
        options:
            max-size: 10m

  # Keycloak identity provider
  keycloak:
    image: openremote/keycloak:latest
    environment:
      TZ: Europe/Zurich

      # Switch to DEBUG to diagnose Keycloak problems.
      KEYCLOAK_LOGLEVEL: INFO

      # The master realm superuser, you should not change this.
      KEYCLOAK_USER: admin

      # Change the admin root password if you make this application publicly accessible! Note
      # that imported demo data uses the admin account and also creates a 'test' user with
      # password 'test'. Importing will be broken if you change the password only here.
      # Demo data should not be imported in production.
      KEYCLOAK_PASSWORD: secret

      # Configure how Keycloak connects to the database
      POSTGRES_DATABASE: openremote
      POSTGRES_USER: openremote
      POSTGRES_PASSWORD: CHANGE_ME_DB_USER_PASSWORD

    # This service needs access to other services on the Docker network.
    links:
      - postgresql

    # Configure logging of the container
    logging:
        options:
            max-size: 10m

  # PostgreSQL DBMS
  postgresql:
    image: openremote/postgresql:latest
    environment:
      TZ: Europe/Zurich
      # This is the DBMS superuser and password. You should change this, especially if you
      # expose the DBMS port and make it accessible externally!
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CHANGE_ME_DB_SUPERUSER_PASSWORD

      # The database and service connection user, passwords should be changed in production!
      POSTGRES_DB: openremote
      OPENREMOTE_USERNAME: openremote
      OPENREMOTE_PASSWORD: CHANGE_ME_DB_USER_PASSWORD

    # Durable data requires a volume mapping on your Docker host
    # volumes:
    #  - /path/to/data/on/my/host/postgresql:/var/lib/postgresql/data

    # Configure logging of the container
    logging:
        options:
            max-size: 10m
