# Demo setup of OpenRemote v3
#
# This configuration works with Docker Community edition (https://docker.com/) on Windows and macOS.
#
# Install Docker Community edition and execute "docker-compose -p openremote -f profile/demo.yml up"
#
version: '2'
services:

  # The frontend proxy, terminates SSL/TLS connections and forwards them to the Manager backend.
  haproxy:

    # Use installed or pull the latest image from Docker Hub.
    image: openremote/haproxy:latest

    environment:

      # It is important that all services have the same timezone and are time synchronized.
      # Bearer tokens are only valid for minutes, and authentication fails if Keycloak drifts.
      TZ: Europe/Zurich

      # This is a demo configuration with a self-signed dummy SSL certificate, baked into the image.
      HAPROXY_CONFIG: /etc/haproxy/demo/haproxy-demo.cfg

    # This service needs access to other services on the Docker network.
    links:
      - manager

    # Expose a public web service mapped to ports on the host.
    ports:
      - "80:80"
      - "443:443"

    # Configure logging of the container
    logging:
        options:
            max-size: 10m

  # The API gateway and Manager web application.
  manager:

    # Use installed or pull the latest image from Docker Hub.
    image: openremote/manager:latest

    environment:

      TZ: Europe/Zurich

      # If developer mode is enabled, all setup tasks will be executed on application startup.
      # This will clean all data in Keycloak and the Manager database, and then import demo/test
      # data. Some caching and other runtime performance-optimizations will also be disabled.
      DEV_MODE: 'false'

      # If you are not running in developer mode, and this is the first time you are starting
      # the application, you can configure which setup tasks you want to execute. Careful,
      # these tasks will clean and populate Keycloak and the Manager database with demo data!
      SETUP_INIT_CLEAN_DATABASE: 'true'
      SETUP_KEYCLOAK_ADMIN_PASSWORD: secret
      SETUP_IMPORT_DEMO_USERS: 'true'
      SETUP_IMPORT_DEMO_ASSETS: 'true'
      SETUP_IMPORT_DEMO_RULES: 'true'

      # Create a demo agent with example configurations for all built-in protocols:
      #
      # - KNX IP gateway
      # - Velbus IP gateway or serial bridge
      # - UPnP (asset discovery only)
      #
      SETUP_IMPORT_DEMO_AGENT: 'true'
      SETUP_IMPORT_DEMO_AGENT_KNX: 'false'
      #SETUP_IMPORT_DEMO_AGENT_KNX_GATEWAY_IP: '10.0.0.11'
      #SETUP_IMPORT_DEMO_AGENT_KNX_LOCAL_IP: '10.0.0.12'
      SETUP_IMPORT_DEMO_AGENT_VELBUS: 'false'
      #SETUP_IMPORT_DEMO_AGENT_VELBUS_COM_PORT: 'COM3'
      SETUP_IMPORT_DEMO_AGENT_UPNP: 'false'
      # TODO: Additional docker settings are necessary to use com ports and multicast from within containers

      # Optional: Configure SMTP smart host for Keycloak, to send password reset emails etc.
      #SETUP_KEYCLOAK_EMAIL_HOST: smtp-host.demo.tld
      #SETUP_KEYCLOAK_EMAIL_USER: 'smtp-user'
      #SETUP_KEYCLOAK_EMAIL_PASSWORD: 'smtp-password'
      #SETUP_KEYCLOAK_EMAIL_PORT: 25
      #SETUP_KEYCLOAK_EMAIL_AUTH: 'true'
      #SETUP_KEYCLOAK_EMAIL_TLS: 'true'
      #SETUP_KEYCLOAK_EMAIL_FROM: 'noreply@demo.tld'

      # The public host name of this OpenRemote installation. This name is used in bearer tokens
      # and must be the name you access the web services under.
      IDENTITY_NETWORK_HOST: localhost

      # Set if SSL is enabled on the frontend reverse proxy and all internal proxies should assume https
      IDENTITY_NETWORK_SECURE: 'true'

      # The public port of this OpenRemote installation.
      IDENTITY_NETWORK_WEBSERVER_PORT: 443

      # The service-internal JDBC connection URL for the database service.
      DATABASE_CONNECTION_URL: jdbc:postgresql://postgresql/openremote

      # The database connection settings, passwords should be changed in production!
      DATABASE_USERNAME: openremote
      DATABASE_PASSWORD: CHANGE_ME_DB_USER_PASSWORD
      DATABASE_MIN_POOL_SIZE: 5
      DATABASE_MAX_POOL_SIZE: 20
      DATABASE_CONNECTION_TIMEOUT_SECONDS: 300

      # The service-internal host name and port of the identity provider.
      KEYCLOAK_HOST: keycloak
      KEYCLOAK_PORT: 8080

      # Optional: Console applications can register for push notifications through FCM.
      # NOTIFICATION_FIREBASE_URL: https://fcm.googleapis.com/fcm/send
      # NOTIFICATION_FIREBASE_API_KEY = '...'

      # Optional: Override built-in logging.properties with a file of your choice.
      # LOGGING_CONFIG_FILE: /my/manager/logging.properties

      # Optional: Provide a path to the map tiles database file (see https://openmaptiles.com/).
      # MAP_TILES_PATH: 'deployment/manager/mapdata.mbtiles'

      # Optional: Override the map settings such as center location and zoom when opening the
      # manager's map, as well as other style details and colours.
      # MAP_SETTINGS_PATH: 'deployment/manager/mapsettings.json'

      # The number of threads and therefore rules engines that can be instantiated (default unlimited).
      # RULES_THREADS_MAX: 32

      # The number of threads and therefore background tasks that can be executed at the same
      # time. Used by scheduled, usually short-lived and non-blocking tasks, such as protocols
      # polling a remote service at regular interval, or the internal checks for expired client
      # subscriptions on the event bus (default depends on detected CPU cores).
      # SCHEDULED_TASKS_THREADS_MAX: 4

      # When asset attributes are enabled for rule events, each value update will be an event fact
      # in a rules knowledge session. You can set the global default expiration time span, after which
      # rule event facts are retracted automatically. Default is 1 hour.
      # RULE_EVENT_EXPIRES: '1h'

      # The identity provider implementation to use for managing user identities, roles, and
      # access authorization. The default is Keycloak, which requires a separate service but
      # provides full multi-tenancy identity and role management. The basic provider supports
      # only superusers and their text passwords, managed in a simple database table.
      # MANAGER_IDENTITY_PROVIDER: 'basic'
      # SETUP_BASIC_IDENTITY_ADMIN_PASSWORD: 'secret'

      # Location of the static manager (UI and API) resources
      # MANAGER_DOCROOT: 'manager/client/src/main/webapp'

      # Location of the static console applications, each subdirectory must have the name of
      # a realm to which the console app belongs.
      # CONSOLE_DOCROOT: 'deployment/manager/resources_console'

    # This service needs access to other services on the Docker network.
    links:
      - postgresql
      - keycloak

    # Override entrypoint for custom JVM options
    # entrypoint:
    #  - "java"
    #  - "-Xmx1024m"
    #  - "-XX:+PrintGCDetails"
    #  - "-cp"
    #  - "/opt/app/lib/*"
    #  - "org.openremote.manager.server.Main"

    # Configure logging of the container, see config/logging.properties
    logging:
        options:
            max-size: 10m

  # Keycloak identity provider
  keycloak:
    image: openremote/keycloak:latest
    environment:
      TZ: Europe/Zurich

      # Switch to DEBUG to diagnose Keycloak problems.
      KEYCLOAK_LOGLEVEL: INFO

      # The master realm superuser, you should not change this.
      KEYCLOAK_USER: admin

      # Change the admin root password if you make this application publicly accessible! Note
      # that imported demo data uses the admin account and also creates a 'test' user with
      # password 'test'. Importing will be broken if you change the password only here.
      # Demo data should not be imported in production.
      KEYCLOAK_PASSWORD: secret

      # Configure how Keycloak connects to the database
      POSTGRES_DATABASE: openremote
      POSTGRES_USER: openremote
      POSTGRES_PASSWORD: CHANGE_ME_DB_USER_PASSWORD

    # This service needs access to other services on the Docker network.
    links:
      - postgresql

    # Configure logging of the container
    logging:
        options:
            max-size: 10m

  # PostgreSQL DBMS
  postgresql:
    image: openremote/postgresql:latest
    environment:
      TZ: Europe/Zurich

      # Create transient database and user. For production, run this once
      # with your volume mapping for the data directory, then remove the
      # variables and restart to preserve the stored data
      POSTGRES_DB: openremote
      POSTGRES_USER: openremote
      POSTGRES_PASSWORD: CHANGE_ME_DB_USER_PASSWORD

      # You can open an SQL console on a running container with:
      # docker exec -it <container ID> psql -U openremote

    # Durable data requires a volume mapping on your Docker host
    # volumes:
    #  - /path/to/data/on/my/host:/var/lib/pgsql/data

    # Configure logging of the container
    logging:
        options:
            max-size: 10m
