# Profile for doing development on the consoles and keycloak theme only.
# Starts haproxy, letsencrypt, keycloak with theme volumed mapped and postgres and exposes haproxy to localhost.
version: '2.2'

volumes:
  proxy-data:
  #manager-data:
  postgresql-data:

services:

  proxy:
    extends:
      file: deploy.yml
      service: proxy
    depends_on:
      manager:
        condition: service_healthy
    volumes:
      - proxy-data:/deployment

  manager:
    extends:
      file: deploy.yml
      service: manager
    environment:
      DEV_MODE: 'true'
    depends_on:
      keycloak:
        condition: service_healthy

  keycloak:
    extends:
      file: deploy.yml
      service: keycloak
    build:
      context: ../keycloak
      dockerfile: dev.Dockerfile
    image: openremote/keycloak_dev:latest
    volumes:
      - ../keycloak/theme:/opt/jboss/keycloak/themes/openremote
    depends_on:
      postgresql:
        condition: service_healthy

  postgresql:
    extends:
      file: deploy.yml
      service: postgresql
    volumes:
      - postgresql-data:/deployment
