#
# Profile for doing IDE development work and running build tests.
#
# Run this in the background for full ./gradlew clean build
#
version: '2.2'

volumes:
  postgresql-data:

services:

  keycloak:
    extends:
      file: deploy.yml
      service: keycloak
    # Access directly if needed on localhost
    ports:
      - "127.0.0.1:8081:8080"
    build:
      context: ../keycloak
      dockerfile: dev.Dockerfile
    image: openremote/keycloak_dev:latest
    volumes:
      - ../ui/keycloak/themes/openremote:/opt/jboss/keycloak/themes/openremote
    depends_on:
      postgresql:
        condition: service_healthy

  postgresql:
    extends:
      file: deploy.yml
      service: postgresql
    # Access directly if needed on localhost
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgresql-data:/data