# Demo setup of OpenRemote v3
#
# This configuration works with https://www.docker.com/products/overview#/docker_toolbox
#
version: '2'
services:

  # This is the API gateway for the whole system and hosting the public resources
  # of the manager web application.
  manager:

    # Use installed or pull the latest image from Docker Hub.
    image: openremote/manager:latest

    # This application exposes a public web service that should be mapped to a host
    # port. The default is '8080', this is the port on your Docker host to access
    # the application. The second '8080' must match the service-internal port (see below).
    ports:
      - "8080:8080"

    # This service needs access to other services on the Docker network.
    links:
      - postgresql
      - keycloak

    environment:

      # It is important that all services have the same timezone and are time synchronized.
      # Bearer tokens are only valid for minutes, and authentication fails if Keycloak drifts.
      TZ: "Europe/Zurich"

      # If dev mode is enabled, caching and other performance-optimizations will be disabled.
      DEV_MODE: 'false'

      # If this is the first time you are starting this stack, and/or with non-durable
      # database (the default), you need to have the database schema created.
      DATABASE_CREATE_SCHEMA: 'true'

      # If this is the first time you are starting this stack, and/or with non-durable
      # database (the default), you might want to work with some automatically imported
      # demo data. The importer uses the Keycloak admin-cli user and the given password.
      DEMO_IMPORT_DATA: 'true'
      DEMO_ADMIN_PASSWORD: secret

      # The service-internal interface and port to listen on. This should not be changed.
      WEBSERVER_LISTEN_HOST: 0.0.0.0
      WEBSERVER_LISTEN_PORT: 8080

      # The public host name of this OpenRemote installation. This name is used in bearer tokens
      # and must be the name you access the web services under. If you are using Docker Toolbox,
      # this is the IP of a virtual machine running the Linux Docker host (see VirtualBox).
      IDENTITY_NETWORK_HOST: '192.168.99.100'

      # The public port of this OpenRemote installation. For simple installations without an
      # HTTP proxy in front of this application, this will be the public webservice host-mapped
      # port.
      IDENTITY_NETWORK_WEBSERVER_PORT: 8080

      # The service-internal JDBC connection URL for the database service.
      DATABASE_CONNECTION_URL: jdbc:postgresql://postgresql/openremote

      # The database connection settings, passwords should be changed in production!
      DATABASE_USERNAME: openremote
      DATABASE_PASSWORD: CHANGE_ME_DB_USER_PASSWORD
      DATABASE_MIN_POOL_SIZE: 5
      DATABASE_MAX_POOL_SIZE: 20
      DATABASE_CONNECTION_TIMEOUT_SECONDS: 300

      # The service-internal host name and port of the identity provider, configured automatically.
      KEYCLOAK_HOST: keycloak
      KEYCLOAK_PORT: 8080

    # Configure logging of the container, see manager/server/conf/logging.properties
    logging:
        options:
            max-size: "10m"
