#
# PostgreSQL DBMS (development)
#
version: '2'
services:

  postgresql_dev:
    build:
      context: ../postgresql
    environment:
      TZ: Europe/Zurich
      # Create transient database and user
      POSTGRES_DB: openremote
      POSTGRES_USER: openremote
      POSTGRES_PASSWORD: CHANGE_ME_DB_USER_PASSWORD
    ports:
      - "5432:5432"