#
# PostgreSQL DBMS
#
version: '2'
services:

  postgresql:
    image: openremote/postgresql:latest
    environment:
      TZ: "Europe/Zurich"
      # This is the DBMS superuser and password. You should change this, especially if you
      # expose the DBMS port and make it accessible externally!
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CHANGE_ME_DB_SUPERUSER_PASSWORD

      # The database and service connection user, passwords should be changed in production!
      POSTGRES_DB: openremote
      OPENREMOTE_USERNAME: openremote
      OPENREMOTE_PASSWORD: CHANGE_ME_DB_USER_PASSWORD
